### PR TITLE
updates story.md templates for new issues

### PR DESCRIPTION
**Pull request by awentzel**
# Pull Request

## Description
This updates the existing template for story issue types

## Reviewer Notes
Please let me know any feedback on this issue. This new template should be clear, concise, and easy to you to enable your workflow so you can achieve greater productivity.

## Test Plan

To be tested after merge as it's the only way to test at this time.

### CODE REVIEW

**Comment by belgamo** [comment]
LGTM! just one question: the issue/story shouldn't be closed at the time we merge the PR, right? Usually, I tag the issue in my PR description using `closes [issue link]` but now since we need to wait for the feature crew review to happen, the issue should remain open until then, correct?

**Review by belgamo — APPROVED** [review]

**Comment by cygleason** [comment]
@awentzel  the taskslists need the three ``` at the bottom, otherwise it's not formatted properly

**Comment by awentzel** [comment]
> LGTM! just one question: the issue/story shouldn't be closed when we merge the PR, right? Usually, I tag the issue in my PR description using `closes [issue link]` but now since we need to wait for the feature crew review to happen, the issue should remain open until then, correct?

You can close this story at the time of merge when all the tasks are completed.

**Comment by awentzel** [comment]
> @awentzel the taskslists need the three ``` at the bottom, otherwise it's not formatted properly

It's at the top and the very bottom of all three lists. It's not separated for each list.

**Review by natebarnz — APPROVED** [review]

**Pull request merged**
